CC=g++
CFLAGS=-Wall -Wextra 
all:
	$(CC) $(CFLAGS) SoundFx.hpp Invader.hpp InvaderFormation.hpp Earth.hpp PlayerLaser.hpp Shield.hpp ShieldWall.hpp CoreCannon.hpp invaders.cpp SoundFx.cpp Invader.cpp InvaderFormation.cpp Earth.cpp PlayerLaser.cpp Shield.cpp ShieldWall.cpp CoreCannon.cpp -lsfml-graphics -lsfml-audio -lsfml-window -lsfml-system -o invaders
