CC=g++
CFLAGS=-Wall -Wextra 
all:
	$(CC) $(CFLAGS) SoundFx.hpp Invader.hpp Earth.hpp PlayerLaser.hpp Shield.hpp CoreCannon.hpp invaders.cpp SoundFx.cpp Invader.cpp Earth.cpp PlayerLaser.cpp Shield.cpp CoreCannon.cpp -lsfml-graphics -lsfml-audio -lsfml-window -lsfml-system -o invaders
