CC=g++
CFLAGS=-Wall -Wextra 
all:
	$(CC) $(CFLAGS) Invader.hpp Earth.hpp PlayerBullet.hpp Shield.hpp CoreCannon.hpp invaders.cpp Invader.cpp Earth.cpp PlayerBullet.cpp Shield.cpp CoreCannon.cpp -lsfml-graphics -lsfml-window -lsfml-system -o invaders
